### ISSUE TITLE
Strange error during page fetching for licence checks

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#55]
Affects both services.

```
I20160620-16:42:07.589(1)? Getting http://linkinghub.elsevier.com/retrieve/pii/S1534580715004268 which resolved to http://linkinghub.elsevier.com/retrieve/pii/S1534580715004268 for licence check
W20160620-16:42:16.314(1)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20160620-16:42:16.316(1)? (STDERR) Trace
W20160620-16:42:16.316(1)? (STDERR)     at Request.addListener (events.js:160:15)
W20160620-16:42:16.316(1)? (STDERR)     at Request.init (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:618:8)
W20160620-16:42:16.316(1)? (STDERR)     at Request.onRequestResponse (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:1127:10)
W20160620-16:42:16.317(1)? (STDERR)     at ClientRequest.emit (events.js:95:17)
W20160620-16:42:16.317(1)? (STDERR)     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1744:21)
W20160620-16:42:16.317(1)? (STDERR)     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
W20160620-16:42:16.317(1)? (STDERR)     at CleartextStream.socketOnData [as ondata] (http.js:1639:20)
W20160620-16:42:16.317(1)? (STDERR)     at CleartextStream.read [as _read] (tls.js:514:12)
W20160620-16:42:16.317(1)? (STDERR)     at CleartextStream.Readable.read (_stream_readable.js:341:10)
W20160620-16:42:16.318(1)? (STDERR)     at EncryptedStream.write [as _write] (tls.js:369:25)
W20160620-16:42:16.318(1)? (STDERR) (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
W20160620-16:42:16.318(1)? (STDERR) Trace
W20160620-16:42:16.318(1)? (STDERR)     at Request.addListener (events.js:160:15)
W20160620-16:42:16.318(1)? (STDERR)     at Request.start (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:937:8)
W20160620-16:42:16.319(1)? (STDERR)     at Request.end (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:1635:10)
W20160620-16:42:16.319(1)? (STDERR)     at end (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:676:14)
W20160620-16:42:16.319(1)? (STDERR)     at Object._onImmediate (/home/emanuil/.meteor/packages/http/.1.1.6.bf9upe++os+web.browser+web.cordova/npm/node_modules/request/request.js:690:7)
W20160620-16:42:16.319(1)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:363:15)

I20160620-16:42:17.424(1)? Error while fetching http://linkinghub.elsevier.com/retrieve/pii/S1534580715004268 for academic licence check.
```

http://linkinghub.elsevier.com/retrieve/pii/S1534580715004268 is just an HTML page. It took a little while to redirect and download (2-3s) in a browser, but it's not a huge PDF or anything (4.2k lines of HTML).

Problem article is

PMCID: PMC4539345
PMID: 26190146
DOI: 10.1016/j.devcel.2015.06.019

**Comment by markmacgillivray** [comment]
I've seen the problem before. The eventEmitter leak happens because too
many redirects are requested, each causing a new node listener. If
something triggers more than 10 of those, it assumes a potential leak. It
is possible to set 10 to a higher number, but I have been unable to
reliably recreate this issue. It only seems to happen, so far, when trying
to resolve certain Elsevier links. My best guess so far is that
occasionally their redirects are incorrectly configured, either
accidentally or on purpose, making it hard to reliably programmatically
retrieve the content. I have already tried various ways of dereferencing
DOIs in advance, but it is possible I should add that more complex
pre-dereference to any Elsevier URL...

**Comment by emanuil-tolev** [comment]
Hmm, if most of the 2-3s was spent by my browser redirecting, I can see the issue. Maybe a lot of interconnected legacy systems, so it resolves eventually (is not a loop) but just jumps through an unusual amount of hoops.

**Comment by markmacgillivray** [comment]
As far as I can tell, this is the case. The more suspicious people in our line of work suggest it may occur on purpose and at random. So far I doubt that though, and have seen no evidence to suggest it.

**Comment by richard-jones** [comment]
@emanuil-tolev @markmacgillivray - is any further action required on this?

**Comment by markmacgillivray** [comment]
No. I have since made some more changes, but it is just an ongoing problem, and the elsevier redirects still occasionally fail.
